exchanges:
  icbc_api_url: "https://papi.icbc.com.cn/exchanges/ns/getLatest"
server:
  port: 8083
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  jackson:
    time-zone: GMT+8