server:
  port: 8091
mybatis:
  mapper-locations: classpath*:mappers/*.xml

spring:
  jackson:
    time-zone: GMT+8
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    enable:
      thread-state: true
      process: true
  server:
    port: 7791
sso:
  jwt:
    public-key:  ${JWT_PUB_KEY}
    private-key:  ${JWT_PRIVATE_KEY}
    expiration:   ${JWT_EXPIRATION}