version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 13316:3306
    container_name: mysql-task-master
    volumes:
      - /data/mysql/hzv/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    command: --ssl=1 --require-secure-transport=ON
  task-master-core:
    image: task-master-core:latest
    container_name: task-master-core
    ports:
      - 8083:8083
    environment:
      - JAVA_OPTS= -Dlog4j.skipJansi=false
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    volumes:
      - /var/log/task-master/core/:/logs

