exchanges:
  icbc_api_url: "https://papi.icbc.com.cn/exchanges/ns/getLatest"
server:
  port: 8083
mybatis:
  mapper-locations: classpath*:mappers/*.xml
spring:
  jackson:
    time-zone: GMT+8
management:
  server:
    address: 127.0.0.1 # 只允许本地访问
    port: 7777
