exchanges:
  icbc_api_url: "https://papi.icbc.com.cn/exchanges/ns/getLatest"
server:
  port: 8083
mybatis:
  mapper-locations: classpath*:mappers/*.xml
spring:
  jackson:
    time-zone: GMT+8
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    web:
      server:
        request:
          metric-name: http.server.requests
    enable:
      thread-state: true
      process: true
  server:
    port: 7783
sso:
  jwt:
    public-key:  ${JWT_PUB_KEY}
    expiration:   ${JWT_EXPIRATION}