spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/task_master_gamma?useSSL=true
    username:  ${MYSQL_USER}
    password:  ${MYSQL_PASSWORD}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
    config: classpath:log4j2-gamma.xml
sso:
  url: http://localhost:8091/